Diamonds Dataset Exploratory Data Analysis

In [3]:
#packages
import pandas as pd
import kagglehub

In [2]:
#downloading the dataset
path = kagglehub.dataset_download("shivam2503/diamonds")
print("Path to dataset files:", path)
#I manually moved the dataset to my data folder in the project after it was downloaded. idk if there's a better way to do that.

Downloading to C:\Users\there\.cache\kagglehub\datasets\shivam2503\diamonds\1.archive...

100%|██████████| 733k/733k [00:00<00:00, 2.26MB/s]

Extracting files...
Path to dataset files: C:\Users\there\.cache\kagglehub\datasets\shivam2503\diamonds\versions\1

In [4]:
diamond_df = pd.read_csv("data/diamonds.csv", index_col = 0)
diamond_df.shape

(53940, 10)

In [10]:
#data validation aka they have all the columns it is said to have
print("Number of Columns: ", diamond_df.shape[1])
print(diamond_df.columns)

Number of Columns:  10
Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='str')

In [ ]:
print(diamond_df.info())
#can check for missing values and the data types of each column

<class 'pandas.DataFrame'>
RangeIndex: 53940 entries, 1 to 53940
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  str
 2   color    53940 non-null  str
 3   clarity  53940 non-null  str
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: float64(6), int64(1), str(3)
memory usage: 4.1 MB
None

In [5]:
#i first called head in the same cell as shape, but shape wouldn't output when i do that
diamond_df.head()

   carat      cut color clarity  depth  table  price     x     y     z
1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
4   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
5   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [6]:
diamond_df.describe()

,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

In [ ]:
#remove rows with null, NaN, values. remove invalid rows

In [ ]:
#create the size column using the x, y, z values

In [ ]:
#sql analyis using duck db